use crate::paths;
use anyhow::{bail, Context, Result};
use std::fs;
use std::io::Write;
use std::path::PathBuf;

const MARKER: &str = "# generated by silo wrap — do not edit";

pub fn cmd_install(names: &[String]) -> Result<()> {
    let bin = paths::bin_dir()?;
    paths::ensure_dir(&bin, false)?;
    let silo = which::which("silo").unwrap_or_else(|_| PathBuf::from("silo"));
    let silo_path = silo.display().to_string();

    let targets: Vec<String> = if names.is_empty() {
        paths::list_profile_names()?
    } else {
        for n in names {
            paths::require_exists(n)?;
        }
        names.to_vec()
    };
    if targets.is_empty() {
        bail!("no profiles to wrap — create some first (`silo bootstrap` / `silo init`)");
    }

    for name in &targets {
        let path = wrapper_path(&bin, name);
        let body = format!(
            "#!/usr/bin/env bash\n{MARKER}\n# silo profile: {name}\nexec \"{silo_path}\" run {name} -- \"$@\"\n"
        );
        let mut f = fs::File::create(&path)
            .with_context(|| format!("write {}", path.display()))?;
        f.write_all(body.as_bytes())?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&path, fs::Permissions::from_mode(0o755))?;
        }
        println!("wrap: {}", path.display());
    }
    println!(
        "installed {} wrapper(s) in {}",
        targets.len(),
        bin.display()
    );
    println!("start: silo-<name>   e.g. silo-{}", targets[0]);
    Ok(())
}

pub fn cmd_uninstall(names: &[String]) -> Result<()> {
    let bin = paths::bin_dir()?;
    let targets: Vec<String> = if names.is_empty() {
        list_managed_wrappers(&bin)?
            .into_iter()
            .filter_map(|p| {
                p.file_name()
                    .and_then(|s| s.to_str())
                    .and_then(|s| s.strip_prefix("silo-"))
                    .map(|s| s.to_string())
            })
            .collect()
    } else {
        names.to_vec()
    };
    if targets.is_empty() {
        println!("(no silo-* wrappers found in {})", bin.display());
        return Ok(());
    }
    for name in &targets {
        let path = wrapper_path(&bin, name);
        if path.is_file() && is_managed(&path)? {
            fs::remove_file(&path)?;
            println!("removed {}", path.display());
        } else if path.is_file() {
            println!("skip {} (not a silo wrap script)", path.display());
        }
    }
    Ok(())
}

pub fn cmd_list() -> Result<()> {
    let bin = paths::bin_dir()?;
    let list = list_managed_wrappers(&bin)?;
    if list.is_empty() {
        println!("(none in {})", bin.display());
        return Ok(());
    }
    for p in list {
        println!("{}", p.display());
    }
    Ok(())
}

fn wrapper_path(bin: &std::path::Path, name: &str) -> PathBuf {
    bin.join(format!("silo-{name}"))
}

fn is_managed(path: &std::path::Path) -> Result<bool> {
    let raw = fs::read_to_string(path)?;
    Ok(raw.contains(MARKER))
}

fn list_managed_wrappers(bin: &std::path::Path) -> Result<Vec<PathBuf>> {
    if !bin.is_dir() {
        return Ok(vec![]);
    }
    let mut out = Vec::new();
    for e in fs::read_dir(bin)? {
        let e = e?;
        let p = e.path();
        let Some(name) = p.file_name().and_then(|s| s.to_str()) else {
            continue;
        };
        if !name.starts_with("silo-") || name == "silo-home" {
            continue;
        }
        // don't delete the main binary if someone named a profile oddly
        if name == "silo" {
            continue;
        }
        if p.is_file() && is_managed(&p).unwrap_or(false) {
            out.push(p);
        }
    }
    out.sort();
    Ok(out)
}
